services:
  # api:
  #   build: .
  #   ports:
  #     - "3000:5000"
  db:
    image: 'postgres:17.2-alpine'
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: access

volumes:
  postgres-data:
